// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnbEeeM1zkKgahhkZWbL6JEAdPrszNM2M',
    appId: '1:816750229887:web:f583dafba7b855296f024a',
    messagingSenderId: '816750229887',
    projectId: 'pet-pal-c7e6b',
    authDomain: 'pet-pal-c7e6b.firebaseapp.com',
    storageBucket: 'pet-pal-c7e6b.appspot.com',
    measurementId: 'G-CGN5ERJXYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXlEV03EmeAkyyW__gzg5-yGKYvJs3bBU',
    appId: '1:816750229887:android:65c31d0dc920b7256f024a',
    messagingSenderId: '816750229887',
    projectId: 'pet-pal-c7e6b',
    storageBucket: 'pet-pal-c7e6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzyFpX5jHYynQ2HLi3TGqC40H2d0oB_sM',
    appId: '1:816750229887:ios:24b1bcf0670c37c16f024a',
    messagingSenderId: '816750229887',
    projectId: 'pet-pal-c7e6b',
    storageBucket: 'pet-pal-c7e6b.appspot.com',
    iosClientId: '816750229887-tu11bt182ea3m0i70egdl9mlf0pgum7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.btlCuoiKiNhom2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzyFpX5jHYynQ2HLi3TGqC40H2d0oB_sM',
    appId: '1:816750229887:ios:24b1bcf0670c37c16f024a',
    messagingSenderId: '816750229887',
    projectId: 'pet-pal-c7e6b',
    storageBucket: 'pet-pal-c7e6b.appspot.com',
    iosClientId: '816750229887-tu11bt182ea3m0i70egdl9mlf0pgum7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.btlCuoiKiNhom2',
  );
}
